### ISSUE TITLE
Nonlinearity in large generative model

### ISSUE THREAD

**Issue by skaae** [facebook/eyescream#4]
You do not seem to be using a nonlinearity in the large generative model?

https://github.com/facebook/eyescream/blob/master/lsun/model.lua#L52

In the small model and in the model generator you use ReLU?  I assume that `__R__` in the
model description is ReLU so I guess its just missing?

**Comment by soumith** [comment]
there is the line:
model_G:add(cudnn.SpatialConvolutionUpsample(3+1, 64, 7, 7, 1, 1)):add(cudnn.ReLU(true))

Maybe you missed the second part of the line which is :add(cudnn.ReLU(true))

**Comment by skaae** [comment]
Yes, I sure did :) Thanks!
